available = {
    "algorithms": [
        {
            "id": "native:buffer",
            "name": "buffer",
            "display_name": "Buffer",
            "short_help_string": "This algorithm computes a buffer area for all the features in an input layer, using a fixed or dynamic distance.\n\nThe segments parameter controls the number of line segments to use to approximate a quarter circle when creating rounded offsets.\n\nThe end cap style parameter controls how line endings are handled in the buffer.\n\nThe join style parameter specifies whether round, miter or beveled joins should be used when offsetting corners in a line.\n\nThe miter limit parameter is only applicable for miter join styles, and controls the maximum distance from the offset curve to use when creating a mitered join.",
            "short_description": "",
            "parameters": [
                {
                    "name": "INPUT",
                    "type": {"name": "vector_layer"},
                    "optional": False,
                    "default": None,
                    "description": "Input layer",
                    "is_destination": False,
                },
                {
                    "name": "DISTANCE",
                    "type": {"name": "float", "minimum": None, "maximum": None},
                    "optional": False,
                    "default": 10,
                    "description": "Distance",
                    "is_destination": False,
                },
                {
                    "name": "SEGMENTS",
                    "type": {"name": "int", "minimum": 1, "maximum": None},
                    "optional": False,
                    "default": 5,
                    "description": "Segments",
                    "is_destination": False,
                },
                {
                    "name": "END_CAP_STYLE",
                    "type": {
                        "name": "enum",
                        "options": ["Round", "Flat", "Square"],
                        "allow_multiple": False,
                    },
                    "optional": False,
                    "default": 0,
                    "description": "End cap style",
                    "is_destination": False,
                },
                {
                    "name": "JOIN_STYLE",
                    "type": {
                        "name": "enum",
                        "options": ["Round", "Miter", "Bevel"],
                        "allow_multiple": False,
                    },
                    "optional": False,
                    "default": 0,
                    "description": "Join style",
                    "is_destination": False,
                },
                {
                    "name": "MITER_LIMIT",
                    "type": {"name": "float", "minimum": 1.0, "maximum": None},
                    "optional": False,
                    "default": 2,
                    "description": "Miter limit",
                    "is_destination": False,
                },
                {
                    "name": "DISSOLVE",
                    "type": {"name": "bool"},
                    "optional": False,
                    "default": False,
                    "description": "Dissolve result",
                    "is_destination": False,
                },
                {
                    "name": "SEPARATE_DISJOINT",
                    "type": {"name": "bool"},
                    "optional": False,
                    "default": False,
                    "description": "Keep disjoint results separate",
                    "is_destination": False,
                },
                {
                    "name": "OUTPUT",
                    "type": {"name": "vector_layer"},
                    "optional": False,
                    "default": None,
                    "description": "Buffered",
                    "is_destination": True,
                },
            ],
            "outputs": [
                {
                    "name": "OUTPUT",
                    "type": {"name": "vector_layer"},
                    "description": "Buffered",
                }
            ],
        },
        {
            "id": "native:centroids",
            "name": "centroids",
            "display_name": "Centroids",
            "short_help_string": "This algorithm creates a new point layer, with points representing the centroid of the geometries in an input layer.\n\nThe attributes associated to each point in the output layer are the same ones associated to the original features.",
            "short_description": "",
            "parameters": [
                {
                    "name": "INPUT",
                    "type": {"name": "vector_layer"},
                    "optional": False,
                    "default": None,
                    "description": "Input layer",
                    "is_destination": False,
                },
                {
                    "name": "ALL_PARTS",
                    "type": {"name": "bool"},
                    "optional": False,
                    "default": False,
                    "description": "Create centroid for each part",
                    "is_destination": False,
                },
                {
                    "name": "OUTPUT",
                    "type": {"name": "vector_layer"},
                    "optional": False,
                    "default": None,
                    "description": "Centroids",
                    "is_destination": True,
                },
            ],
            "outputs": [
                {
                    "name": "OUTPUT",
                    "type": {"name": "vector_layer"},
                    "description": "Centroids",
                }
            ],
        },
        {
            "id": "native:concavehull",
            "name": "concavehull",
            "display_name": "Concave hull",
            "short_help_string": "This algorithm computes the concave hull of the features from an input layer.",
            "short_description": "",
            "parameters": [
                {
                    "name": "INPUT",
                    "type": {"name": "vector_layer"},
                    "optional": False,
                    "default": None,
                    "description": "Input layer",
                    "is_destination": False,
                },
                {
                    "name": "ALPHA",
                    "type": {"name": "float", "minimum": None, "maximum": 1.0},
                    "optional": False,
                    "default": 0.3,
                    "description": "Threshold (0-1, where 1 is equivalent with Convex Hull)",
                    "is_destination": False,
                },
                {
                    "name": "HOLES",
                    "type": {"name": "bool"},
                    "optional": False,
                    "default": True,
                    "description": "Allow holes",
                    "is_destination": False,
                },
                {
                    "name": "NO_MULTIGEOMETRY",
                    "type": {"name": "bool"},
                    "optional": False,
                    "default": False,
                    "description": "Split multipart geometry into singleparts",
                    "is_destination": False,
                },
                {
                    "name": "OUTPUT",
                    "type": {"name": "vector_layer"},
                    "optional": False,
                    "default": None,
                    "description": "Concave hull",
                    "is_destination": True,
                },
            ],
            "outputs": [
                {
                    "name": "OUTPUT",
                    "type": {"name": "vector_layer"},
                    "description": "Concave hull",
                }
            ],
        },
        {
            "id": "native:rasterlayerproperties",
            "name": "rasterlayerproperties",
            "display_name": "Raster layer properties",
            "short_help_string": "This algorithm returns basic properties of the given raster layer, including the extent, size in pixels and dimensions of pixels (in map units).\n\nIf an optional band number is specified then the NoData value for the selected band will also be returned.",
            "short_description": "",
            "parameters": [
                {
                    "name": "INPUT",
                    "type": {"name": "raster_layer"},
                    "optional": False,
                    "default": None,
                    "description": "Input layer",
                    "is_destination": False,
                },
                {
                    "name": "BAND",
                    "type": {"name": "band", "allow_multiple": False},
                    "optional": True,
                    "default": None,
                    "description": "Band number",
                    "is_destination": False,
                },
            ],
            "outputs": [
                {
                    "name": "X_MIN",
                    "type": {"name": "float", "minimum": None, "maximum": None},
                    "description": "Minimum x-coordinate",
                },
                {
                    "name": "X_MAX",
                    "type": {"name": "float", "minimum": None, "maximum": None},
                    "description": "Maximum x-coordinate",
                },
                {
                    "name": "Y_MIN",
                    "type": {"name": "float", "minimum": None, "maximum": None},
                    "description": "Minimum y-coordinate",
                },
                {
                    "name": "Y_MAX",
                    "type": {"name": "float", "minimum": None, "maximum": None},
                    "description": "Maximum y-coordinate",
                },
                {
                    "name": "EXTENT",
                    "type": {"name": "str", "length": None},
                    "description": "Extent",
                },
                {
                    "name": "PIXEL_WIDTH",
                    "type": {"name": "float", "minimum": None, "maximum": None},
                    "description": "Pixel size (width) in map units",
                },
                {
                    "name": "PIXEL_HEIGHT",
                    "type": {"name": "float", "minimum": None, "maximum": None},
                    "description": "Pixel size (height) in map units",
                },
                {
                    "name": "CRS_AUTHID",
                    "type": {"name": "str", "length": None},
                    "description": "CRS authority identifier",
                },
                {
                    "name": "WIDTH_IN_PIXELS",
                    "type": {"name": "float", "minimum": None, "maximum": None},
                    "description": "Width in pixels",
                },
                {
                    "name": "HEIGHT_IN_PIXELS",
                    "type": {"name": "float", "minimum": None, "maximum": None},
                    "description": "Height in pixels",
                },
                {
                    "name": "HAS_NODATA_VALUE",
                    "type": {"name": "bool"},
                    "description": "Band has a NoData value set",
                },
                {
                    "name": "NODATA_VALUE",
                    "type": {"name": "float", "minimum": None, "maximum": None},
                    "description": "Band NoData value",
                },
                {
                    "name": "BAND_COUNT",
                    "type": {"name": "float", "minimum": None, "maximum": None},
                    "description": "Number of bands in raster",
                },
            ],
        },
        {
            "id": "native:rescaleraster",
            "name": "rescaleraster",
            "display_name": "Rescale raster",
            "short_help_string": "Rescales raster layer to a new value range, while preserving the shape (distribution) of the raster's histogram (pixel values). Input values are mapped using a linear interpolation from the source raster's minimum and maximum pixel values to the destination minimum and maximum pixel range.\n\nBy default the algorithm preserves the original NoData value, but there is an option to override it.",
            "short_description": "",
            "parameters": [
                {
                    "name": "INPUT",
                    "type": {"name": "raster_layer"},
                    "optional": False,
                    "default": None,
                    "description": "Input raster",
                    "is_destination": False,
                },
                {
                    "name": "BAND",
                    "type": {"name": "band", "allow_multiple": False},
                    "optional": False,
                    "default": 1,
                    "description": "Band number",
                    "is_destination": False,
                },
                {
                    "name": "MINIMUM",
                    "type": {"name": "float", "minimum": None, "maximum": None},
                    "optional": False,
                    "default": 0,
                    "description": "New minimum value",
                    "is_destination": False,
                },
                {
                    "name": "MAXIMUM",
                    "type": {"name": "float", "minimum": None, "maximum": None},
                    "optional": False,
                    "default": 255,
                    "description": "New maximum value",
                    "is_destination": False,
                },
                {
                    "name": "NODATA",
                    "type": {"name": "float", "minimum": None, "maximum": None},
                    "optional": True,
                    "default": None,
                    "description": "New NoData value",
                    "is_destination": False,
                },
                {
                    "name": "CREATE_OPTIONS",
                    "type": {"name": "str", "length": None},
                    "optional": True,
                    "default": None,
                    "description": "Creation options",
                    "is_destination": False,
                },
                {
                    "name": "OUTPUT",
                    "type": {"name": "raster_layer"},
                    "optional": False,
                    "default": None,
                    "description": "Rescaled",
                    "is_destination": True,
                },
            ],
            "outputs": [
                {
                    "name": "OUTPUT",
                    "type": {"name": "raster_layer"},
                    "description": "Rescaled",
                }
            ],
        },
        {
            "id": "native:collect",
            "name": "collect",
            "display_name": "Collect geometries",
            "short_help_string": "This algorithm takes a vector layer and collects its geometries into new multipart geometries. One or more attributes can be specified to collect only geometries belonging to the same class (having the same value for the specified attributes), alternatively all geometries can be collected.\n\nAll output geometries will be converted to multi geometries, even those with just a single part. This algorithm does not dissolve overlapping geometries - they will be collected together without modifying the shape of each geometry part.\n\nSee the 'Promote to multipart' or 'Aggregate' algorithms for alternative options.",
            "short_description": "",
            "parameters": [
                {
                    "name": "INPUT",
                    "type": {"name": "vector_layer"},
                    "optional": False,
                    "default": None,
                    "description": "Input layer",
                    "is_destination": False,
                },
                {
                    "name": "FIELD",
                    "type": {"name": "field", "allow_multiple": True},
                    "optional": True,
                    "default": None,
                    "description": "Unique ID fields",
                    "is_destination": False,
                },
                {
                    "name": "OUTPUT",
                    "type": {"name": "vector_layer"},
                    "optional": False,
                    "default": None,
                    "description": "Collected",
                    "is_destination": True,
                },
            ],
            "outputs": [
                {
                    "name": "OUTPUT",
                    "type": {"name": "vector_layer"},
                    "description": "Collected",
                }
            ],
        },
        {
            "id": "native:rasterize",
            "name": "rasterize",
            "display_name": "Convert map to raster",
            "short_help_string": "This algorithm rasterizes map canvas content.\n\nA map theme can be selected to render a predetermined set of layers with a defined style for each layer. Alternatively, a set of layers can be selected if no map theme is set. If neither map theme nor layer is set, all the visible layers in the set extent will be rendered.\n\nThe minimum extent entered will internally be extended to a multiple of the tile size.",
            "short_description": "Renders the map canvas to a raster file.",
            "parameters": [
                {
                    "name": "EXTENT",
                    "type": {"name": "extent"},
                    "optional": False,
                    "default": None,
                    "description": "Minimum extent to render",
                    "is_destination": False,
                },
                {
                    "name": "EXTENT_BUFFER",
                    "type": {"name": "float", "minimum": None, "maximum": None},
                    "optional": True,
                    "default": 0,
                    "description": "Buffer around tiles in map units",
                    "is_destination": False,
                },
                {
                    "name": "TILE_SIZE",
                    "type": {"name": "int", "minimum": 64, "maximum": None},
                    "optional": False,
                    "default": 1024,
                    "description": "Tile size",
                    "is_destination": False,
                },
                {
                    "name": "MAP_UNITS_PER_PIXEL",
                    "type": {"name": "float", "minimum": None, "maximum": None},
                    "optional": True,
                    "default": 100,
                    "description": "Map units per pixel",
                    "is_destination": False,
                },
                {
                    "name": "MAKE_BACKGROUND_TRANSPARENT",
                    "type": {"name": "bool"},
                    "optional": False,
                    "default": False,
                    "description": "Make background transparent",
                    "is_destination": False,
                },
                {
                    "name": "MAP_THEME",
                    "type": {"name": "map_theme"},
                    "optional": True,
                    "default": None,
                    "description": "Map theme to render",
                    "is_destination": False,
                },
                {
                    "name": "LAYERS",
                    "type": {
                        "name": "multiple_layers",
                        "layer_type": {"name": "map_layer"},
                        "minimum": 0,
                    },
                    "optional": True,
                    "default": None,
                    "description": "Layers to render",
                    "is_destination": False,
                },
                {
                    "name": "OUTPUT",
                    "type": {"name": "raster_layer"},
                    "optional": False,
                    "default": None,
                    "description": "Output layer",
                    "is_destination": True,
                },
            ],
            "outputs": [
                {
                    "name": "OUTPUT",
                    "type": {"name": "raster_layer"},
                    "description": "Output layer",
                }
            ],
        },
        {
            "id": "native:affinetransform",
            "name": "affinetransform",
            "display_name": "Affine transform",
            "short_help_string": "Applies an affine transformation to the geometries from a layer. Affine transformations can include translation, scaling and rotation. The operations are performed in a scale, rotation, translation order.\n\nZ and M values present in the geometry can also be translated and scaled independently.",
            "short_description": "Applies an affine transformation to geometries.",
            "parameters": [
                {
                    "name": "INPUT",
                    "type": {"name": "vector_layer"},
                    "optional": False,
                    "default": None,
                    "description": "Input layer",
                    "is_destination": False,
                },
                {
                    "name": "DELTA_X",
                    "type": {"name": "float", "minimum": None, "maximum": None},
                    "optional": False,
                    "default": 0.0,
                    "description": "Translation (x-axis)",
                    "is_destination": False,
                },
                {
                    "name": "DELTA_Y",
                    "type": {"name": "float", "minimum": None, "maximum": None},
                    "optional": False,
                    "default": 0.0,
                    "description": "Translation (y-axis)",
                    "is_destination": False,
                },
                {
                    "name": "DELTA_Z",
                    "type": {"name": "float", "minimum": None, "maximum": None},
                    "optional": False,
                    "default": 0.0,
                    "description": "Translation (z-axis)",
                    "is_destination": False,
                },
                {
                    "name": "DELTA_M",
                    "type": {"name": "float", "minimum": None, "maximum": None},
                    "optional": False,
                    "default": 0.0,
                    "description": "Translation (m values)",
                    "is_destination": False,
                },
                {
                    "name": "SCALE_X",
                    "type": {"name": "float", "minimum": None, "maximum": None},
                    "optional": False,
                    "default": 1.0,
                    "description": "Scale factor (x-axis)",
                    "is_destination": False,
                },
                {
                    "name": "SCALE_Y",
                    "type": {"name": "float", "minimum": None, "maximum": None},
                    "optional": False,
                    "default": 1.0,
                    "description": "Scale factor (y-axis)",
                    "is_destination": False,
                },
                {
                    "name": "SCALE_Z",
                    "type": {"name": "float", "minimum": None, "maximum": None},
                    "optional": False,
                    "default": 1.0,
                    "description": "Scale factor (z-axis)",
                    "is_destination": False,
                },
                {
                    "name": "SCALE_M",
                    "type": {"name": "float", "minimum": None, "maximum": None},
                    "optional": False,
                    "default": 1.0,
                    "description": "Scale factor (m values)",
                    "is_destination": False,
                },
                {
                    "name": "ROTATION_Z",
                    "type": {"name": "float", "minimum": None, "maximum": None},
                    "optional": False,
                    "default": 0.0,
                    "description": "Rotation around z-axis (degrees counter-clockwise)",
                    "is_destination": False,
                },
                {
                    "name": "OUTPUT",
                    "type": {"name": "vector_layer"},
                    "optional": False,
                    "default": None,
                    "description": "Transformed",
                    "is_destination": True,
                },
            ],
            "outputs": [
                {
                    "name": "OUTPUT",
                    "type": {"name": "vector_layer"},
                    "description": "Transformed",
                }
            ],
        },
    ]
}
