services:
  qsl:
    env_file:
      - .env
    environment:
      - "QSL_REDIS_URL=redis://redis:6379"
      - "QSL_SVG_PATH=/io/svg"
      - "QSL_DATA_ROOT=/io/data"
    platform: "linux/amd64"
    image: local/qsl:dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        PYTHON_VERSION: "${PY_VERSION:-3.12}"
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    deploy:
      replicas: ${REPLICAS}
    develop:
      watch:
        - action: rebuild
          path: uv.lock
        - action: rebuild
          path: Dockerfile
    volumes:
      - ./:/app
      - ./tests/resources/projects:/io/data
      - ./tests/resources/svg:/io/svg
      - qsl-venv:/home/appuser/.venv
      # this is the actual entrypoint, but it calls /bin/dev.start.sh
      - ./docker/dev.entrypoint.sh:/bin/dev.entrypoint.sh
      # we change name of the script as dev.entrypoint.sh expect it!
      - ./docker/dev.start.worker.sh:/bin/dev.start.sh
    entrypoint: [ "/bin/dev.entrypoint.sh" ]
    ports:
      # we expose the ssh which is running in the container for DEV access
      - "4223:2222"
    depends_on:
      redis:
        condition: service_healthy
  redis:
    image: redis:8.8.0
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 0.5s
      retries: 50
  qsl-exporter:
    env_file:
      - .env
    environment:
      - "QSL_DATA_ROOT=/io/data"
    platform: "linux/amd64"
    image: local/qsl-exporter:dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        PYTHON_VERSION: "${PY_VERSION:-3.12}"
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    deploy:
      replicas: ${REPLICAS}
    develop:
      watch:
        - action: rebuild
          path: uv.lock
        - action: rebuild
          path: Dockerfile
    volumes:
      - ./:/app
      - ./tests/resources/projects:/io/data
      - ./tests/resources/svg:/io/svg
      - qsl-venv:/home/appuser/.venv
      - ./docker/dev.start.exporter_api.sh:/bin/dev.start.sh
    entrypoint: [ "/bin/dev.start.sh" ]
    ports:
      # we expose the ssh which is running in the container for DEV access
      - "5555:5000"
volumes:
  qsl-venv:
