services:
  qgis-server-light:
    image: opengisch/qgis-server-light-dev:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    restart: unless-stopped
    command:
      - "run-reload"
    environment:
      - "QSL_REDIS_URL=redis://redis"
    volumes:
      - "./:/app"
    deploy:
      replicas: ${QSL_REPLICAS}
  redis:
    image: redis:7.4.0
    ports:
      - "1234:6379"
