site_name: QGIS-Server-Light
docs_dir: src
nav:
  - index.md
  - General Idea: general_idea.md
  - Prerequisites: prerequisites.md
  - Usage of Worker:
    - CLI: usage.worker.cli.md
    - Local: usage.worker.local.md
    - Docker: usage.worker.docker.md
  - Usage of Exporter: usage.exporter.md
  - Usage of interface: usage.interface.md
  - Dev the project: dev.md
  - ApiDoc:
    - Interface: interface.md
    - Worker: worker.md
    - Exporter: exporter.md
theme:
  name: material
plugins:
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [../src]
          options:
            show_submodules: true
            show_if_no_docstring: true
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
