name: Build docs
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TX_TOKEN: ${{ secrets.TX_TOKEN }}
    steps:
      - name: Prepare Build Environment
        run: |
          cp .env.compose.example .env
          echo "UID=$(id -u)" >> .env
          echo "GID=$(id -g)" >> .env
          cat .env
      - name: Build QGIS-Server-Light Image
        run: |
          docker compose build qsl
      - name: Build docs
        run: docker compose run --rm --entrypoint bash qsl -c "uv run mkdocs build -f docs/mkdocs.yml -d site"
      - uses: actions/upload-artifact@v7
        with:
          name: docs
          path: docs/site
          if-no-files-found: error
      - name: Deploy to GitHub Pages
        run: docker compose run --rm --entrypoint bash qsl -c "uv run mkdocs gh-deploy -f docs/mkdocs.yml -d site --force"
