name: Build Docker Images

on:
  push:
    branches:
      - master

jobs:
  docker-image-latest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build release
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        cache-from: type=local,src=cache
        tags: opengisch/qgis-server-light:latest
  docker-image-latest-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build release
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          target: dev
          cache-from: type=local,src=cache
          tags: opengisch/qgis-server-light-dev:latest
