name: TestSuite
on:
  push:
    branches:
      - "*"
    tags:
      - v*

jobs:
  test-py:
    name: Test Python
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        qgis-slim-version:
          - '3.40'
          - '3.44'
    steps:
      - uses: actions/checkout@v6
      - name: Prepare Build Environment
        run: |
          cp .env.compose.example .env
          echo "QGIS_VERSION=${{ matrix.qgis-slim-version }}" >> .env
          echo "UID=$(id -u)" >> .env
          echo "GID=$(id -g)" >> .env
          cat .env
      - name: Build QGIS-Server-Light Image
        run: |
          docker compose build qsl
      - name: Run tests
        run: docker compose run --rm --entrypoint bash qsl -c "uv run pytest"
